CREATE TABLE mtg_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT as IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    nickname TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
)