INSERT INTO mtg_cards (name, image)
    VALUES
    ('Alpine Watchdog', 'https://media.wizards.com/2020/m21/en_kS7LiunFPF.png'),
    ('Angelic Ascension', 'https://media.wizards.com/2020/m21/en_Fhm1Wg8TTo.png'),
    ('Anointed Chorister', 'https://media.wizards.com/2020/m21/en_BemoNRF97j.png'),
    ('Aven Gagglemaster', 'https://media.wizards.com/2020/m21/en_jar3bmBCQK.png'),
    ('Baneslayer Angel', 'https://media.wizards.com/2020/m21/en_QpR2bppWIh.png'),
    ('Basri Ket', 'https://media.wizards.com/2020/m21/en_ANLe6JkcUt.png'),
    ('Basri''s Acolyte', 'https://media.wizards.com/2020/m21/en_zfvj01VQNI.png'),
    ('Basri''s Lieutenant', 'https://media.wizards.com/2020/m21/en_8mAIcjWVTC.png'),
    ('Basri''s Solidarity', 'https://media.wizards.com/2020/m21/en_IF6fcXWcot.png'),
    ('Celestial Enforcer', 'https://media.wizards.com/2020/m21/en_RmMWC9cU34.png'),
    ('Concordia Pegasus', 'https://media.wizards.com/2020/m21/en_dmvqh2lmb1.png'),
    ('Containment Priest', 'https://media.wizards.com/2020/m21/en_zAvg3U4SX2.png'),
    ('Daybreak Charger', 'https://media.wizards.com/2020/m21/en_wp7nVUSafb.png'),
    ('Defiant Strike', 'https://media.wizards.com/2020/m21/en_BhSJoyMGfH.png'),
    ('Dub', 'https://media.wizards.com/2020/m21/en_sc9UdVyqfj.png'),
    ('Faith''s Fetters', 'https://media.wizards.com/2020/m21/en_UtYNI4pwN0.png'),
    ('Falconer Adept', 'https://media.wizards.com/2020/m21/en_EH9KNUrQgz.png'),
    ('Feat of Resistance', 'https://media.wizards.com/2020/m21/en_dCrt9NaeAr.png'),
    ('Gale Swooper', 'https://media.wizards.com/2020/m21/en_UKQeOZuDyD.png'),
    ('Glorious Anthem', 'https://media.wizards.com/2020/m21/en_K2TDGIwYc6.png'),
    ('Griffin Aerie', 'https://media.wizards.com/2020/m21/en_ujWY8rwaF2.png'),
    ('Idol of Endurance', 'https://media.wizards.com/2020/m21/en_EIDu2tMkxO.png'),
    ('Legion''s Judgment', 'https://media.wizards.com/2020/m21/en_DfuA9Mi6Vw.png'),
    ('Light of Promise', 'https://media.wizards.com/2020/m21/en_cLTTGZbdO4.png'),
    ('Makeshift Batallion', 'https://media.wizards.com/2020/m21/en_O0O14cmfIO.png'),
    ('Mangara, the Diplomat', 'https://media.wizards.com/2020/m21/en_bkIZsFy16t.png'),
    ('Nine Lives', 'https://media.wizards.com/2020/m21/en_SBXhQBqzWM.png'),
    ('Pack Leader', 'https://media.wizards.com/2020/m21/en_lsdZp7uc7L.png'),
    ('Rambunctious Mutt', 'https://media.wizards.com/2020/m21/en_bK1KbNzv3X.png'),
    ('Revitalize', 'https://media.wizards.com/2020/m21/en_fRT2yjH82D.png'),
    ('Runed Halo', 'https://media.wizards.com/2020/m21/en_eI2feiIHvb.png'),
    ('Sanctum of Tranquil Light', 'https://media.wizards.com/2020/m21/en_794bg31Vce.png'),
    ('Selfless Savior', 'https://media.wizards.com/2020/m21/en_hxLHgqqwFW.png'),
    ('Siege Striker', 'https://media.wizards.com/2020/m21/en_x1fmrY70fQ.png'),
    ('Speaker of the Heavens', 'https://media.wizards.com/2020/m21/en_a3wpVicN8i.png'),
    ('Staunch Shieldmate', 'https://media.wizards.com/2020/m21/en_NniXnIMKP5.png'),
    ('Swift Response', 'https://media.wizards.com/2020/m21/en_UHqWDeXbp8.png'),
    ('Tempered Veteran', 'https://media.wizards.com/2020/m21/en_JR2VHnoFZY.png'),
    ('Valorous Steed', 'https://media.wizards.com/2020/m21/en_zGldl2WSMe.png'),
    ('Vryn Wingmare', 'https://media.wizards.com/2020/m21/en_DVlSrfFNn3.png'),
    ('Warded Battlements', 'https://media.wizards.com/2020/m21/en_0KNWRZbQRl.png'),
    ('Plains', 'https://media.wizards.com/2020/m21/en_UmtsBzIGXt.png')